# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

demeanIndMat <- function(x, n_periods, N) {
    .Call(`_PAGFL_demeanIndMat`, x, n_periods, N)
}

fdIndMat <- function(x, n_periods, N) {
    .Call(`_PAGFL_fdIndMat`, x, n_periods, N)
}

buildDiagX <- function(X, n_periods, N, groups) {
    .Call(`_PAGFL_buildDiagX`, X, n_periods, N, groups)
}

PAGFL_Algo <- function(y, X, X_block, n_periods, method, Z, bias_correc, lambda, kappa, min_group_frac, max_iter, tol_convergence, tol_group) {
    .Call(`_PAGFL_PAGFL_Algo`, y, X, X_block, n_periods, method, Z, bias_correc, lambda, kappa, min_group_frac, max_iter, tol_convergence, tol_group)
}

IC <- function(estimOutput, y, X_block, rho) {
    .Call(`_PAGFL_IC`, estimOutput, y, X_block, rho)
}

