# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bspline_system <- function(x, d, knots, intercept) {
    .Call(`_PAGFL_bspline_system`, x, d, knots, intercept)
}

demeanIndVec <- function(x, N, i_index) {
    .Call(`_PAGFL_demeanIndVec`, x, N, i_index)
}

buildDiagX_block <- function(X, N, i_index, groups) {
    .Call(`_PAGFL_buildDiagX_block`, X, N, i_index, groups)
}

pagfl_routine <- function(y, X, method, Z, i_index, t_index, N, bias_correc, lambda_vec, kappa, min_group_frac, max_iter, tol_convergence, tol_group, varrho, rho) {
    .Call(`_PAGFL_pagfl_routine`, y, X, method, Z, i_index, t_index, N, bias_correc, lambda_vec, kappa, min_group_frac, max_iter, tol_convergence, tol_group, varrho, rho)
}

tv_pagfl_routine <- function(y, X, X_const, d, M, i_index, t_index, N, p_const, lambda_vec, kappa, min_group_frac, max_iter, tol_convergence, tol_group, varrho, rho, verbose) {
    .Call(`_PAGFL_tv_pagfl_routine`, y, X, X_const, d, M, i_index, t_index, N, p_const, lambda_vec, kappa, min_group_frac, max_iter, tol_convergence, tol_group, varrho, rho, verbose)
}

getTVAlpha <- function(xi, K_hat, p, n_periods, B) {
    .Call(`_PAGFL_getTVAlpha`, xi, K_hat, p, n_periods, B)
}

delete_missing_t <- function(i_index, t_index, K_hat, groups_hat, alpha_hat) {
    .Call(`_PAGFL_delete_missing_t`, i_index, t_index, K_hat, groups_hat, alpha_hat)
}

fitMeasures <- function(N, k, residuals, y, i_index) {
    .Call(`_PAGFL_fitMeasures`, N, k, residuals, y, i_index)
}

getFE <- function(y, i_index, N, method) {
    .Call(`_PAGFL_getFE`, y, i_index, N, method)
}

